services:
  logger:
    build:
      context: ./services/logger
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./services/logger:/app
      - ~/.gradle:/root/.gradle
    working_dir: /app
    environment:
      - JAVA_TOOL_OPTIONS=-Dio.ktor.development=true
    command: >
      bash -c "
        ./gradlew -t build -x test &      # 継続的ビルド
        ./gradlew run -Pio.ktor.development=true
      "
